# Generated by Django 5.0.3 on 2024-03-31 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post1_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post1",
            name="author",
        ),
    ]
